### ISSUE TITLE
tagを付与してもアニメーションが実行されない

### ISSUE THREAD

**Issue by takumaru0311** [TCMB-Project/TCMB-Train-Kit#1]

**Comment by hako1152** [comment]
[tcmb_prototype_controller.txt](https://github.com/TCMB-Project/TCMB-Train-Kit/files/8758407/tcmb_prototype_controller.txt)
このアニコンで試してみてください。
（アップロードの都合により.txtファイルになってます）

**Comment by hako1152** [comment]
このアニコンを使ったところアニコンが原因かはよくわからないです。
eventコマンドでdest1を実行したところ正常に実行されたのでコンポーネントグループかアニコンがおかしいと考えています。
